name: Generate Animation

on:
  schedule:
    - cron: "0 */12 * * *" # Executa a cada 12 horas
  workflow_dispatch: # Permite rodar manualmente

jobs:
  build:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ Generate Snake Animation SVG
        uses: Platane/snk@v2.2.1
        with:
          github_user_name: Igor-Ponso
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: ğŸš€ Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
